language: r

r: bioc-devel
warnings_are_errors: false
sudo: false
cache: packages

r_packages:
  - covr

r_github_packages:
  - r-hub/rhub

r_build_args: "--no-manual --no-resave-data"
r_check_args: "--no-build-vignettes --no-manual --timings"

after_success:
  - Rscript -e "library(covr); codecov(); library(rhub); validate_email('leo.collado@libd.org', 'e4717b56dde7421e8806e7b16777fa22'); check(Sys.getenv('PKG_TARBALL'), c('windows-x86_64-devel', 'debian-gcc-devel'))"

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    secure: Xhgymko2l6p9e1glsHFDv1oFHoG4X0iSuMZTKEwCD46hm1dTXMN1CmF1XGxUMnFoK9B4a4Nq7yCXb9WFWLlMVgcrLVGgvv8raLw/WScrpEU1xjYPrH3BeBjXeaTCP5zrlMvVCTQdipR6/TOIsC5gvpvfB3iU1KWMQkCLe5WVscw/jXjY6Kgm0GEldIodPBjH+E4IGEM9T5z2EIkAibwZm58OGLc1PMe80K3pP1BKpByeirqgQbGmANY7cjSwg2O9pP78QpMThRqNoWVTRa6B+C0FczUnGHuayttN/8a6g+PeFsIl2HqN7wS2DePfAuvDUShanDXMlIqY06h3y715Y5EInfTafK3FVYSb+IKj7IeZT4uuVX/pQQXSKLo2K//gif7Amk/7eiwOP43nIEOaD+Uus0yP7sMBgQV1VB/ZWROyDmLcXYtuXVzwKZ1AwjEUgh/a8K6uz2htpznO52iC83oqt+V8qcdoQzk47B36O0Bd0yDccS7EtTk8uXm6e7J/0iSZzgqsUdxU+010x9HYPJ3sAcKEcD7O89QmHV0h7XIBzQekM9LYIVMlDqpRmDHVRrYVMEPT49YqqRCUj61N/2cdlzwUMsGoWWQa6MF7t9zzAK6bRdeo/MKcH8loEtJLfn4dUs5lWzeyycxM/Ufk7SBBxAGfhxFJxVZA1spltcA=

env:
  global:
    - _R_CHECK_TIMINGS_="0"
