language: r

r: bioc-devel
warnings_are_errors: false
sudo: false
cache: packages

r_packages:
  - covr

r_github_packages:
  - r-hub/rhub

r_build_args: "--no-manual --no-resave-data"
r_check_args: "--no-build-vignettes --no-manual --timings"

after_success:
  - Rscript -e "library(covr); codecov(); library(rhub); validate_email('leo.collado@libd.org', 'e4717b56dde7421e8806e7b16777fa22'); check(Sys.getenv('PKG_TARBALL'), c('windows-x86_64-devel', 'debian-gcc-devel'))"

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    secure: uVinCdbZtsv+fzjENcgan+qyDyvf4gI0fYAWbI81jSpXIZmXpbSc+ltdoFLxw1oZIN9hqFJeK3jVjzNb7uFFqeQhNaSkwBMfjg6ufX0YPk2GaiprwVgF0GNqXXlHk89VHeHW3oKnXExdaIx/ecYMq1V6puyRf5HYa+Z+ltHSPsEE0mhfwjTsCOFxm4ex7H5o+vNHXcpSfzV/cAkWPwYhucVBoOdHSdW9cbvLvgoph8ZjKcN7rIUxyrT6Ho1TZlE6w4pVYq+tjfHtyRjXpCBWJwyf0WMbatJQnc9a7U48IRm5YpY/7WkNSCNLmZv/d3Aih72gIeL9Q90PLPJbHtKkxiZjyNCGmh5bHrz8VE5LWSko/dU3vupo6rIiUdj13qhPQxIYUFy0Jc8lPAX5gAh7nj5+eVFqwuubuQgbE3FOYppw3Ys/pPK9F7/FeYEqdz73Msk/3JqluoRuQrCTjxXhH1NMlv0Nmkqmd6LHWhIfZQpP3HJlD695EEn6Sd8VcK8Cmz04LdYIrKecDXzDioa3jH4zrhR1TgkAQJToWk58d/10eu16spJk05XlptRU//s+su6bvFLQEfd7XP6JKcQ4y7i6ke10FiHf4hDO4yI4Vd4ChwEKJBjTMXGKNW0Vxy9cXBGeKMNj2Q9h4+BeIoYqtHLxIY5iNBytUBg75BgFXz4=

env:
  global:
    - _R_CHECK_TIMINGS_="0"
