language: r

r: bioc-devel
warnings_are_errors: false
sudo: false
cache: packages

r_packages:
  - covr

r_github_packages:
  - r-hub/rhub

r_build_args: "--no-manual --no-resave-data"
r_check_args: "--no-build-vignettes --no-manual --timings"

after_success:
  - Rscript -e "library(covr); codecov(); library(rhub); validate_email('leo.collado@libd.org', 'e4717b56dde7421e8806e7b16777fa22'); check(Sys.getenv('PKG_TARBALL'), c('windows-x86_64-devel', 'debian-gcc-devel'))"

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    secure: ZhN2s3ilAY6GjGi7hbO0FSHYFEViaOO1BNX1Sn2Ts6qa3WwmNzq432VDddCiTsdmw/AisC+0eh8bsd/yVlf/UU8f97sZooVFTUwsgpI+y3OInWdeQlMWhi2+n3Ar+B8vzhCbY814tbZ7jizay8QIro/aKwifna3nHWx0VFYWr1/h0w8+UBeBuZFxkjnHhxZAnz7sg+aTPPbtZuiuLm6guGdets4XkW62Mxc5QNN6s+Y2m9cEHNKxCi7zsgMBskMQDt6S2kVQoMrHfX3x+iyJxRvMO/8hIRg6w/MAk/LJE/SsPptU0ubwQAgZzwJMg67G5WznT37kQyWqsW/uIBvy5VkT9mMw9bhLXXhp07m1XWZIF5RwNPSB1TeYYyT6Pg5VG5Gw8rh0urEfwQOugkmXRsUTl+mWIQS4/T2UJdKcVYykxgH2kl1rEVzqLvcCFZ8d2sN20fuSGOuRpXTMdC4RKV78cslQWHxWEdRvDE1T7s6ByJDF50bWv1uqlMLQljG6i8Pwc5PoIDeZZNuvxWJTxpY8VMpPVdBUqqr/8l3yAXjDAlBkkC53aZogSM7e4EXHZ1cK0K/Pe4rmELwWJjLmhFJ8GnX18cCmBxhayPnkOLEIJOO33bVc2VXrW2pOox2Pk8LqL44aZmIGwnJA95PUt71VE/SvHbYyoDKw3To3skw=

env:
  global:
    - _R_CHECK_TIMINGS_="0"
